package:
  create: 
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.0.0"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
  deploy:
    set:
      domain: bigbang.dev
      public_key_file: bigbang.dev.key
      public_cert_file: bigbang.dev.cert
      name: "big-bang-aws" # maybe inject something here for the GH PR?
      # eks_oidc_provider_arn: # this needs to be set for deployment

      # loki_kms_key_alias: "ad3132309"
