name: CICD Pipeline Testing
on: [push]

jobs:
  create_pacakge:
    runs-on: ubuntu-latest

    name: Build Big Bang Distros
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          
      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.25.0

      - name: Create DUBBD
        run: zarf package create --confirm
        working-directory: defense-unicorns-distro

      - name: Create CocoWow
        run: zarf package create --confirm
        working-directory: cocowow