name: CICD Pipeline Testing
on: [push]

jobs:
  create_pacakge:
    runs-on: ubuntu-latest

    name: Build Big Bang Distros
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          
      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.25.0

      - name: Create DUBBD
        run: zarf package create --confirm
        working-directory: defense-unicorns-distro

      - name: Create CocoWow
        run: zarf package create --confirm
        working-directory: cocowow
      - name: Create DUBBD AWS 
        run: zarf package create --confirm
        working-directory: aws

      # - name: login DUBBD
      #   run: zarf tools registry login ghcr.io -u runyontr -p ${GH_PAT}
      # - name: publish DUBBD
      #   run: zarf package publish zarf-package-big-bang-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/packages/big-bang-distro
      #   working-directory: defense-unicorns-distro
      # - name: publish DUBBD
      #   run: zarf package publish zarf-package-big-bang-aws-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/packages/big-bang-distro-aws
      #   working-directory: aws